### ISSUE TITLE
Rearranging it to a proper quarto extension?

### ISSUE THREAD

**Issue by chainsawriot** [ccr-journal/ccr-quarto#3]
https://quarto.org/docs/journals/formats.html

So that one can

```sh
quarto use template vanatteveldt/ccr-quarto ## This work
## These dont, no _extensions/
## quarto install extension vanatteveldt/ccr-quarto
## quarto render article.qmd --to ccr-pdf
## quarto render article.qmd --to ccr-html
```

I can give it a shot.

**Comment by vanatteveldt** [comment]
That would be fantastic!!

**Comment by vanatteveldt** [comment]
Thanks so much, this is great!

It does produce a compile error as it defaults to xelatex. We can support this easily by putting the font expansion microtype in an if statement in the template, I can have a look at it tomorrow. 

`Package microtype Error: Font expansion does not work with xetex.`
